import type { ExecutionTrace } from './types';

export const sampleCode = `def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

result = factorial(3)
print(result)`;

export const mockTrace: ExecutionTrace = [
  {
    step: 0,
    line: 7,
    highlightedLine: 1,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [{ id: 'main_1', name: '<module>', line: 7, locals: {} }],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 1,
    line: 1,
    highlightedLine: 1,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
      { id: 'main_1', name: '<module>', line: 7, locals: {} },
      { id: 'fact1_2', name: 'factorial', line: 1, locals: { n: 3 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 2,
    line: 2,
    highlightedLine: 2,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
      { id: 'main_1', name: '<module>', line: 7, locals: {} },
      { id: 'fact1_2', name: 'factorial', line: 2, locals: { n: 3 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 3,
    line: 5,
    highlightedLine: 5,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
      { id: 'main_1', name: '<module>', line: 7, locals: {} },
      { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 4,
    line: 1,
    highlightedLine: 1,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
      { id: 'main_1', name: '<module>', line: 7, locals: {} },
      { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
      { id: 'fact2_3', name: 'factorial', line: 1, locals: { n: 2 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 5,
    line: 2,
    highlightedLine: 2,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
      { id: 'main_1', name: '<module>', line: 7, locals: {} },
      { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
      { id: 'fact2_3', name: 'factorial', line: 2, locals: { n: 2 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 6,
    line: 5,
    highlightedLine: 5,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
      { id: 'main_1', name: '<module>', line: 7, locals: {} },
      { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
      { id: 'fact2_3', name: 'factorial', line: 5, locals: { n: 2 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 7,
    line: 1,
    highlightedLine: 1,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
      { id: 'main_1', name: '<module>', line: 7, locals: {} },
      { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
      { id: 'fact2_3', name: 'factorial', line: 5, locals: { n: 2 } },
      { id: 'fact3_4', name: 'factorial', line: 1, locals: { n: 1 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 8,
    line: 2,
    highlightedLine: 2,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
        { id: 'main_1', name: '<module>', line: 7, locals: {} },
        { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
        { id: 'fact2_3', name: 'factorial', line: 5, locals: { n: 2 } },
        { id: 'fact3_4', name: 'factorial', line: 2, locals: { n: 1 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 9,
    line: 5,
    highlightedLine: 5,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
        { id: 'main_1', name: '<module>', line: 7, locals: {} },
        { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
        { id: 'fact2_3', name: 'factorial', line: 5, locals: { n: 2 } },
        { id: 'fact3_4', name: 'factorial', line: 5, locals: { n: 1 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 10,
    line: 1,
    highlightedLine: 1,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
        { id: 'main_1', name: '<module>', line: 7, locals: {} },
        { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
        { id: 'fact2_3', name: 'factorial', line: 5, locals: { n: 2 } },
        { id: 'fact3_4', name: 'factorial', line: 5, locals: { n: 1 } },
        { id: 'fact4_5', name: 'factorial', line: 1, locals: { n: 0 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 11,
    line: 2,
    highlightedLine: 2,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
        { id: 'main_1', name: '<module>', line: 7, locals: {} },
        { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
        { id: 'fact2_3', name: 'factorial', line: 5, locals: { n: 2 } },
        { id: 'fact3_4', name: 'factorial', line: 5, locals: { n: 1 } },
        { id: 'fact4_5', name: 'factorial', line: 2, locals: { n: 0 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 12,
    line: 3,
    highlightedLine: 3,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
        { id: 'main_1', name: '<module>', line: 7, locals: {} },
        { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
        { id: 'fact2_3', name: 'factorial', line: 5, locals: { n: 2 } },
        { id: 'fact3_4', name: 'factorial', line: 5, locals: { n: 1 } },
        { id: 'fact4_5', name: 'factorial', line: 3, locals: { n: 0, __return__: 1 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 13,
    line: 5,
    highlightedLine: 5,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
      { id: 'main_1', name: '<module>', line: 7, locals: {} },
      { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
      { id: 'fact2_3', name: 'factorial', line: 5, locals: { n: 2 } },
      { id: 'fact3_4', name: 'factorial', line: 5, locals: { n: 1, __return__: 1 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 14,
    line: 5,
    highlightedLine: 5,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
        { id: 'main_1', name: '<module>', line: 7, locals: {} },
        { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3 } },
        { id: 'fact2_3', name: 'factorial', line: 5, locals: { n: 2, __return__: 2 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 15,
    line: 5,
    highlightedLine: 5,
    globals: { factorial: 'ref_func_factorial' },
    callStack: [
        { id: 'main_1', name: '<module>', line: 7, locals: {} },
        { id: 'fact1_2', name: 'factorial', line: 5, locals: { n: 3, __return__: 6 } },
    ],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 16,
    line: 7,
    highlightedLine: 7,
    globals: { factorial: 'ref_func_factorial', result: 6 },
    callStack: [{ id: 'main_1', name: '<module>', line: 7, locals: {} }],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '',
  },
  {
    step: 17,
    line: 8,
    highlightedLine: 8,
    globals: { factorial: 'ref_func_factorial', result: 6 },
    callStack: [{ id: 'main_1', name: '<module>', line: 8, locals: {} }],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '6\n',
  },
  {
    step: 18,
    line: 8,
    highlightedLine: 8,
    globals: { factorial: 'ref_func_factorial', result: 6 },
    callStack: [{ id: 'main_1', name: '<module>', line: 8, locals: { __return__: 'None' } }],
    heap: { func_factorial: { type: 'function', name: 'factorial(n)' } },
    output: '6\n',
  },
];
